### ISSUE TITLE
Nros without Branch Instructions on Mac

### ISSUE THREAD

**Issue by natehaxx** [reswitched/libtransistor#135]
I was trying to build the Nros from Scratch and was checking them with Ryujinx and here is the log.

00000000ms | INFO  > Loading as homebrew.
 00000000ms | INFO  > Image base at 0x0000000008000000.

Unhandled Exception: Ryujinx.Core.OsHle.Exceptions.UndefinedInstructionException: The instruction at 0x0000000008000000 (opcode 0x00000000) is undefined!
   at Ryujinx.Core.OsHle.Process.UndefinedHandler(Object sender, AInstUndefinedEventArgs e) in /Users/DJAlexDaCosta/Ryujinx/Ryujinx.Core/OsHle/Process.cs:line 215
   at Sub0000000008000000(AThreadState , AMemory )
   at ChocolArm64.ATranslator.ExecuteSubroutine(AThread Thread, Int64 Position) in /Users/DJAlexDaCosta/Ryujinx/ChocolArm64/ATranslator.cs:line 71
   at ChocolArm64.AThread.<Execute>b__23_0() in /Users/DJAlexDaCosta/Ryujinx/ChocolArm64/AThread.cs:line 58
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

now since Libtransistor is building inside dist i cant get any nro to build correctly on my system.

**Comment by misson20000** [comment]
please attach your broken NRO

**Comment by natehaxx** [comment]
[picodrive.nro.zip](https://github.com/reswitched/libtransistor/files/1815172/picodrive.nro.zip)

**Comment by misson20000** [comment]
I'm lead to believe that there is something wrong with your environment by that nobody else has encountered this problem. Make sure you're using recent versions of LLVM, LLD, Clang, etc., delete your whole libtransistor source tree, reclone, rebuild, etc., delete your whole picodrive/retroarch source tree too, reclone, rebuild, etc.

**Comment by natehaxx** [comment]
i did that the issue might be that i am using Clang 6.0 and an Beta Version of XCode

**Comment by misson20000** [comment]
This seems to be a problem introduced by LLD somewhere between 5.0.1 and 6.0.0.
